--- # Multiple Tasks on Multiple Servers in Single Playbook
- hosts: Master
  tasks:
  - name: Install httpd on centos Servers
    yum: pkg=lynx state=installed update_cache=true
  - name: Querying for Telnet Install
    yum: pkg=telnet state=present update_cache=true
 
- hosts: agents
  tasks:
  - name: Install telnet on Local Server
    yum: pkg=telnet state=installed update_cache=true
  - name: Querying for Httpd Install
    yum: pkg=httpd state=present update_cache=true
