---
- hosts: localhost
  gather_facts: no
  connection: local

  vars:
    s3_bucket_name: "your-unique-s3-bucket-name"
    aws_region: "us-east-1"
    aws_access_key: "your_access_key"
    aws_secret_key: "your_secret_key"

  tasks:
    - name: Create S3 bucket
      amazon.aws.aws_s3:
        name: "{{ s3_bucket_name }}"
        mode: create
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: s3_result

    - name: Display result
      debug:
        var: s3_result
