---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    region: us-east-1
    availability_zone: us-east-1a
    volume_size: 10
    volume_type: gp2
    aws_access_key: "your_access_key"
    aws_secret_key: "your_secret_key"

  tasks:
    - name: Create an EBS volume
      ec2_vol:
        region: "{{ region }}"
        zone: "{{ availability_zone }}"
        volume_type: "{{ volume_type }}"
        volume_size: "{{ volume_size }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: new_volume

    - name: Show new volume details
      debug:
        var: new_volume
